"""empty message

Revision ID: b432a655332e
Revises: 
Create Date: 2023-05-15 16:45:29.689861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'b432a655332e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_number', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('crypto_impact', sa.Text(), nullable=True),
    sa.Column('dcta_analysis', sa.Text(), nullable=True),
    sa.Column('timestamp', sqlite.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_number')
    )
    op.create_table('bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_number', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('st', sa.String(length=20), nullable=False),
    sa.Column('session', sa.String(length=50), nullable=False),
    sa.Column('introduced', sa.DateTime(), nullable=True),
    sa.Column('latest_action', sa.String(length=200), nullable=True),
    sa.Column('latest_action_date', sa.DateTime(), nullable=True),
    sa.Column('primary_sponsor', sa.String(length=100), nullable=True),
    sa.Column('cosponsors', sa.String(length=500), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('short_subject', sa.String(length=30), nullable=True),
    sa.Column('open_states_url', sa.String(length=200), nullable=True),
    sa.Column('latest_bill_text_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_number')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_number', sa.String(length=50), nullable=False),
    sa.Column('st', sa.String(length=20), nullable=False),
    sa.Column('event_date', sqlite.DATETIME(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('bill')
    op.drop_table('analysis')
    # ### end Alembic commands ###
